# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
    { on = ["g", "h"], run = "cd ~", desc = "~/" },
    { on = ["g", "t"], run = "cd /tmp", desc = "/tmp" },
    { on = ["g", "c"], run = "cd ~/code", desc = "~/code" },
    { on = ["g", "d"], run = "cd ~/hq", desc = "~/hq" },
    { on = ["g", "<Space>"], run = "cd --interactive", desc = "Jump to" },
]
