theme = "modus_vivendi_tintedp"

[editor]
line-number = "relative"
# Renders a line at the top of the editor displaying open buffers
bufferline = "multiple"
# Remove the annoying vertical ruler. The formatter already handles long lines.
rulers = []

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.auto-save]
focus-lost = true # default: false
after-delay.enable = true # default: false
