includes = [".dotter/include/debian.toml"]

packages = [
    #
    # Shell
    "shell",
    "fish",
    # "nushell",
    #
    # Terminals
    # "wezterm",
    # "alacritty",
    "ghostty",
    "zellij",
    "starship",
    "atuin",
    #
    # Fetchers
    "fastfetch",
    #
    # Editor
    "helix",
    "neovide",
    #
    # Scripts
    "bin",
    #
    # VSC
    "git",
    "jj",
    #
    # Utils
    "fontconfig",
    "gnupg",
    # "zellij",
    "yazi",
    # "lla",
    "eget",
    "jjui",
    #
    # Browsers
    # "tridactyl",
    #
    # Programming Languages
    "cargo",
]

[variables]
multiplexer = "zellij"
editor = "hx"
terminal_font_size = 21

font = "Maple Mono NF" # 21. Friendly
# font = "0xProto Nerd Font" # 21. Too much noise.

# Available theme can be found in shells/fish/colors.fish
theme = "modus_vivendi"
