name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Check code quality
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - uses: taiki-e/install-action@v2
        with:
          tool: just,dprint,typos

      - name: Show version information
        shell: bash
        run: |
          dprint --version

      - name: Check
        run: |
          just check
